import React, { useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";

import Sidebar from "./Sidebar";
import { apiFetch } from "./api";

function AlertsPage() {
    const navigate = useNavigate();

    const [alerts, setAlerts] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState("");

    const loadAlerts = useCallback(async () => {
        try {
            setLoading(true);
            setError("");

            const data = await apiFetch("/api/alerts");

            setAlerts(Array.isArray(data) ? data : []);
        } catch (err) {
            console.error("Alert loading error:", err);

            if (
                err?.message?.includes("401") ||
                err?.message?.includes("403")
            ) {
                localStorage.clear();
                navigate("/login");
                return;
            }

            setError("Unable to load alerts.");
        } finally {
            setLoading(false);
        }
    }, [navigate]);

    useEffect(() => {
        loadAlerts();
    }, [loadAlerts]);

    const resolveAlert = async (id) => {
        if (!window.confirm("Resolve this alert?")) {
            return;
        }

        try {
            await apiFetch(`/api/alerts/${id}/resolve`, {
                method: "PUT",
            });

            loadAlerts();
        } catch (err) {
            alert("Unable to resolve alert.");
            console.error(err);
        }
    };

    const getAlertType = (alert) => {
        const value = (
            alert?.alertType ||
            alert?.type ||
            alert?.severity ||
            ""
        )
            .toString()
            .toUpperCase();

        if (
            value.includes("CRITICAL") ||
            value.includes("URGENT")
        ) {
            return "critical";
        }

        if (
            value.includes("WARNING") ||
            value.includes("LOW")
        ) {
            return "warning";
        }

        return "info";
    };

    const getAlertIcon = (type) => {
        if (type === "critical") return "🚨";
        if (type === "warning") return "⚠️";
        return "🔔";
    };

    const getTitle = (alert) => {
        return (
            alert?.title ||
            alert?.alertType ||
            alert?.type ||
            "System Alert"
        );
    };

    const getMessage = (alert) => {
        return (
            alert?.message ||
            alert?.description ||
            alert?.alertMessage ||
            "An alert has been generated by the system."
        );
    };

    const getDate = (alert) => {
        const value =
            alert?.createdAt ||
            alert?.alertDate ||
            alert?.createdDate;

        if (!value) {
            return "Date unavailable";
        }

        return new Date(value).toLocaleString();
    };

    return (
        <>
            <style>{`
                .alerts-page {
                    min-height: 100vh;
                    display: flex;
                    background:
                        radial-gradient(
                            circle at 90% 10%,
                            rgba(239,68,68,.08),
                            transparent 25%
                        ),
                        #f8fafc;
                    font-family:
                        "DM Sans",
                        "Segoe UI",
                        sans-serif;
                }

                .alerts-main {
                    flex: 1;
                    min-width: 0;
                    overflow-y: auto;
                }

                .alerts-content {
                    max-width: 1500px;
                    margin: auto;
                    padding: 35px 38px;
                }

                .alerts-header {
                    display: flex;
                    justify-content: space-between;
                    align-items: center;
                    margin-bottom: 30px;
                }

                .alerts-title {
                    margin: 0;
                    font-size: 32px;
                    font-weight: 800;
                    color: #0f172a;
                }

                .alerts-subtitle {
                    margin-top: 7px;
                    color: #64748b;
                    font-size: 14px;
                }

                .alert-summary {
                    display: grid;
                    grid-template-columns: repeat(3, 1fr);
                    gap: 18px;
                    margin-bottom: 25px;
                }

                .summary-card {
                    padding: 20px;
                    background: white;
                    border-radius: 17px;
                    border: 1px solid #e2e8f0;
                    box-shadow:
                        0 5px 20px
                        rgba(15,23,42,.06);
                }

                .summary-icon {
                    width: 45px;
                    height: 45px;
                    border-radius: 13px;
                    display: flex;
                    align-items: center;
                    justify-content: center;
                    font-size: 21px;
                    margin-bottom: 13px;
                }

                .summary-label {
                    color: #64748b;
                    font-size: 11px;
                    font-weight: 700;
                    text-transform: uppercase;
                }

                .summary-value {
                    margin-top: 5px;
                    font-size: 29px;
                    font-weight: 800;
                }

                .alerts-container {
                    background: white;
                    border-radius: 20px;
                    border: 1px solid #e2e8f0;
                    padding: 25px;
                    box-shadow:
                        0 5px 20px
                        rgba(15,23,42,.05);
                }

                .alerts-container-header {
                    display: flex;
                    justify-content: space-between;
                    align-items: center;
                    margin-bottom: 20px;
                }

                .section-title {
                    margin: 0;
                    font-size: 19px;
                    font-weight: 800;
                    color: #0f172a;
                }

                .refresh-button {
                    border: none;
                    padding: 9px 14px;
                    border-radius: 9px;
                    background: #eef2ff;
                    color: #4f46e5;
                    font-weight: 700;
                    cursor: pointer;
                }

                .alert-item {
                    display: flex;
                    align-items: flex-start;
                    gap: 15px;
                    padding: 18px;
                    margin-bottom: 12px;
                    border-radius: 14px;
                    border: 1px solid;
                    transition: .2s ease;
                }

                .alert-item:hover {
                    transform: translateY(-2px);
                    box-shadow:
                        0 7px 18px
                        rgba(15,23,42,.07);
                }

                .alert-item.critical {
                    background: #fff1f2;
                    border-color: #fecdd3;
                }

                .alert-item.warning {
                    background: #fff7ed;
                    border-color: #fed7aa;
                }

                .alert-item.info {
                    background: #eff6ff;
                    border-color: #bfdbfe;
                }

                .alert-icon {
                    width: 44px;
                    height: 44px;
                    flex-shrink: 0;
                    border-radius: 12px;
                    display: flex;
                    align-items: center;
                    justify-content: center;
                    font-size: 20px;
                    background: white;
                }

                .alert-content {
                    flex: 1;
                }

                .alert-title {
                    font-size: 14px;
                    font-weight: 800;
                    color: #0f172a;
                }

                .alert-message {
                    margin-top: 5px;
                    color: #475569;
                    font-size: 13px;
                    line-height: 1.5;
                }

                .alert-date {
                    margin-top: 7px;
                    color: #94a3b8;
                    font-size: 11px;
                }

                .resolve-button {
                    border: none;
                    padding: 8px 12px;
                    border-radius: 8px;
                    background: #16a34a;
                    color: white;
                    font-size: 11px;
                    font-weight: 700;
                    cursor: pointer;
                }

                .resolve-button:hover {
                    background: #15803d;
                }

                .empty-alerts {
                    padding: 70px 20px;
                    text-align: center;
                    color: #94a3b8;
                }

                .empty-alert-icon {
                    font-size: 48px;
                    margin-bottom: 12px;
                }

                .error-message {
                    padding: 14px;
                    border-radius: 10px;
                    background: #fef2f2;
                    color: #991b1b;
                    margin-bottom: 20px;
                }

                @media(max-width:800px) {
                    .alerts-content {
                        padding: 22px;
                    }

                    .alert-summary {
                        grid-template-columns: 1fr;
                    }

                    .alerts-header {
                        align-items: flex-start;
                        flex-direction: column;
                        gap: 15px;
                    }

                    .alert-item {
                        flex-direction: column;
                    }
                }
            `}</style>

            <div className="alerts-page">
                <Sidebar />

                <main className="alerts-main">
                    <div className="alerts-content">

                        <div className="alerts-header">
                            <div>
                                <h1 className="alerts-title">
                                    🚨 Alerts
                                </h1>

                                <p className="alerts-subtitle">
                                    Monitor important blood bank
                                    system notifications.
                                </p>
                            </div>

                            <button
                                className="refresh-button"
                                onClick={loadAlerts}
                            >
                                ↻ Refresh
                            </button>
                        </div>

                        {error && (
                            <div className="error-message">
                                ⚠️ {error}
                            </div>
                        )}

                        <div className="alert-summary">

                            <div className="summary-card">
                                <div
                                    className="summary-icon"
                                    style={{
                                        background: "#fff1f2",
                                        color: "#e11d48",
                                    }}
                                >
                                    🚨
                                </div>

                                <div className="summary-label">
                                    Total Alerts
                                </div>

                                <div
                                    className="summary-value"
                                    style={{
                                        color: "#e11d48",
                                    }}
                                >
                                    {alerts.length}
                                </div>
                            </div>

                            <div className="summary-card">
                                <div
                                    className="summary-icon"
                                    style={{
                                        background: "#fff7ed",
                                        color: "#f97316",
                                    }}
                                >
                                    ⚠️
                                </div>

                                <div className="summary-label">
                                    Warnings
                                </div>

                                <div
                                    className="summary-value"
                                    style={{
                                        color: "#f97316",
                                    }}
                                >
                                    {
                                        alerts.filter(
                                            (a) =>
                                                getAlertType(a) ===
                                                "warning"
                                        ).length
                                    }
                                </div>
                            </div>

                            <div className="summary-card">
                                <div
                                    className="summary-icon"
                                    style={{
                                        background: "#fef2f2",
                                        color: "#dc2626",
                                    }}
                                >
                                    🔴
                                </div>

                                <div className="summary-label">
                                    Critical
                                </div>

                                <div
                                    className="summary-value"
                                    style={{
                                        color: "#dc2626",
                                    }}
                                >
                                    {
                                        alerts.filter(
                                            (a) =>
                                                getAlertType(a) ===
                                                "critical"
                                        ).length
                                    }
                                </div>
                            </div>

                        </div>

                        <div className="alerts-container">

                            <div className="alerts-container-header">
                                <h2 className="section-title">
                                    Active Alerts
                                </h2>

                                <span
                                    style={{
                                        color: "#64748b",
                                        fontSize: 12,
                                    }}
                                >
                                    {alerts.length} active
                                </span>
                            </div>

                            {loading ? (
                                <div className="empty-alerts">
                                    Loading alerts...
                                </div>
                            ) : alerts.length === 0 ? (
                                <div className="empty-alerts">

                                    <div className="empty-alert-icon">
                                        ✅
                                    </div>

                                    <strong
                                        style={{
                                            color: "#334155",
                                        }}
                                    >
                                        No active alerts
                                    </strong>

                                    <div style={{ marginTop: 5 }}>
                                        Everything looks good.
                                    </div>

                                </div>
                            ) : (
                                alerts.map((alert) => {

                                    const type =
                                        getAlertType(alert);

                                    return (
                                        <div
                                            className={`alert-item ${type}`}
                                            key={
                                                alert.alertId ||
                                                alert.id ||
                                                Math.random()
                                            }
                                        >

                                            <div className="alert-icon">
                                                {getAlertIcon(type)}
                                            </div>

                                            <div className="alert-content">

                                                <div className="alert-title">
                                                    {getTitle(alert)}
                                                </div>

                                                <div className="alert-message">
                                                    {getMessage(alert)}
                                                </div>

                                                <div className="alert-date">
                                                    {getDate(alert)}
                                                </div>

                                            </div>

                                            {(alert.alertId ||
                                                alert.id) && (
                                                <button
                                                    className="resolve-button"
                                                    onClick={() =>
                                                        resolveAlert(
                                                            alert.alertId ||
                                                            alert.id
                                                        )
                                                    }
                                                >
                                                    Resolve
                                                </button>
                                            )}

                                        </div>
                                    );
                                })
                            )}

                        </div>

                    </div>
                </main>
            </div>
        </>
    );
}

export default AlertsPage;